import { NextRequest, NextResponse } from "next/server";
import sgMail from '@sendgrid/mail';

export async function POST(request: NextRequest) {
  try {
    const { sessionId, email, summary, subject: subjectParam } = await request.json();

    // Parse Subject and Body from summary if possible
    let subject = subjectParam || "Your Visit Summary";
    let body = summary;

    // Backward compatibility: try to parse subject from summary if not provided
    if (!subjectParam && summary.startsWith("Subject:")) {
      const parts = summary.split("\n\n");
      if (parts.length >= 2) {
        const subjectLine = parts[0];
        subject = subjectLine.replace("Subject:", "").trim();
        body = parts.slice(1).join("\n\n");
      }
    }

    // Send email using SendGrid if API key is present
    if (process.env.SENDGRID_API_KEY) {
      sgMail.setApiKey(process.env.SENDGRID_API_KEY);
      
      const msg = {
        to: email,
        from: process.env.SENDGRID_FROM_EMAIL || 'adarsh.danda1@gmail.com', // Must be verified in SendGrid
        subject: subject,
        text: body,
        html: `
          <div style="font-family: sans-serif; white-space: pre-wrap;">
            ${body.replace(/\n/g, '<br/>')}
          </div>
          <hr/>
          <p><em>Generated by Clinical Action Layer</em></p>
        `,
      };

      try {
        const response = await sgMail.send(msg);
        console.log(`[Email] Sent aftercare summary to: ${email}`);
        console.log('[Email] SendGrid response:', JSON.stringify(response, null, 2));
      } catch (emailError: any) {
        console.error('❌ Failed to send email:', emailError);
        if (emailError.response) {
          console.error('❌ SendGrid error response:', emailError.response.body);
        }
        throw emailError;
      }
    } else {
      console.warn('[Email] SENDGRID_API_KEY not found. Simulating email send.');
      console.log(`[Mock Email] Subject: ${subject}`);
      console.log(`[Mock Email] Body length: ${body.length} characters`);
      // Simulate delay
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }

    return NextResponse.json({
      success: true,
      message: `After-care summary sent to ${email}`,
      sentAt: new Date().toISOString(),
    });
  } catch (error) {
    console.error("Error in send-aftercare:", error);
    return NextResponse.json(
      { error: "Failed to send aftercare email" },
      { status: 500 }
    );
  }
}
